### ISSUE TITLE
Alternative Gatways

### ISSUE THREAD

**Issue by karneaud** [vanilophp/payment#2]
Hi,

Does/ Can Vanilo incorporate  gateways built with the Omnipay framework?

**Comment by fulopattila122** [comment]
Sorry for the super late response. I've been thinking about it in the last weeks and I'm leaning towards the idea to build an Omnipay bridge for Vanilo Payments.

Any further thoughts on that from your side?

**Comment by karneaud** [comment]
@fulopattila122 

I've had some success building custom payment gateways for [invoiceninja](https://github.com/invoiceninja/invoiceninja ) and I'm looking at doing something similar with [crater](https://github.com/bytefury/crater) which doesn't have a design pattern for such integrations as yet...I'm looking into using [modules](https://github.com/nWidart/laravel-modules) to accomplish this.

**Comment by adrienne** [comment]
Has anything ever happened with this, @fulopattila122 ?

**Comment by fulopattila122** [comment]
> Has anything ever happened with this, @fulopattila122 ?

No, not yet. Currently, it's not among the plans for the next 2 months.

**Comment by fulopattila122** [comment]
Update on this: currently it's not on our roadmap to build an OmniPay bridge for Vanilo Payments.
If anyone is interested in building it please drop me a line, I'll be happy to help with the specs (what would be required from Vanilo side).

In the meantime, we've added a skeleton for building new payment gateways: https://github.com/vanilophp/payment-gateway-skeleton
It's a good starting point to use that package and bootstrap a new gateway with it.
